"""
Email sender abstraction — CASL-compliant.

Behaviour:
- If RESEND_API_KEY is set in env, sends via Resend HTTP API.
- Otherwise, all outgoing messages are queued into the `email_outbox`
  Mongo collection with status="pending". They CAN be replayed once
  Resend is connected (see /api/admin/email-outbox/flush).

CASL-mandated footer is appended to every commercial message:
- Sender identification (name + BC address + phone + email)
- One-click unsubscribe link (already generated by the caller)
- Purpose statement

The `kind` field distinguishes:
- "transactional" — verification, unsubscribe confirmations, receipts.
  These do NOT require CASL consent (implied consent by user action).
- "commercial" — listing alerts, newsletters. Requires verified opt-in.

Every send is logged to `email_outbox` for audit trail (CASL requires
3-year retention of consent + all messages sent).
"""
from __future__ import annotations
import os
import logging
from datetime import datetime, timezone
from typing import Optional

import httpx

logger = logging.getLogger("email_sender")

# CASL identification block (immutable — do NOT strip when composing emails)
SENDER_NAME    = "Doug LeMaire, REALTOR® · EZtoFind.ca"
SENDER_ORG     = "Fraser Property Management Realty Services Ltd."
SENDER_ADDRESS = "1 – 22374 Lougheed Hwy, Maple Ridge, BC V2X 2T5"
SENDER_PHONE   = "+1-604-466-7021"
SENDER_EMAIL   = "info@eztofind.ca"

RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "").strip()
RESEND_FROM    = os.environ.get("RESEND_FROM", "EZtoFind.ca <alerts@eztofind.ca>")
RESEND_URL     = "https://api.resend.com/emails"


def casl_footer_html(unsubscribe_url: str) -> str:
    """CASL-mandated footer. Included on EVERY commercial message."""
    return f"""
<hr style="margin:2rem 0 1rem;border:none;border-top:1px solid #e5e7eb"/>
<div style="font-size:12px;color:#6b7280;line-height:1.6;font-family:Inter,Arial,sans-serif">
  <p style="margin:0 0 0.5rem"><strong>{SENDER_NAME}</strong><br/>
  {SENDER_ORG}<br/>
  {SENDER_ADDRESS} · {SENDER_PHONE} · <a href="mailto:{SENDER_EMAIL}" style="color:#0F2A5B">{SENDER_EMAIL}</a></p>
  <p style="margin:0 0 0.5rem">You are receiving this because you signed up for BC real-estate listing alerts on EZtoFind.ca and confirmed your email address. Under CASL you can opt out of these messages at any time.</p>
  <p style="margin:0"><a href="{unsubscribe_url}" style="color:#0F2A5B;text-decoration:underline">Unsubscribe with one click</a> · <a href="https://eztofind.ca/privacy" style="color:#0F2A5B;text-decoration:underline">Privacy Policy (PIPA)</a></p>
</div>
""".strip()


def casl_footer_text(unsubscribe_url: str) -> str:
    """Plain-text version of the CASL footer."""
    return (
        f"\n\n---\n"
        f"{SENDER_NAME}\n"
        f"{SENDER_ORG}\n"
        f"{SENDER_ADDRESS} · {SENDER_PHONE} · {SENDER_EMAIL}\n\n"
        f"You are receiving this because you signed up for BC real-estate listing alerts "
        f"on EZtoFind.ca and confirmed your email address. Under CASL you can opt out "
        f"at any time.\n\n"
        f"Unsubscribe with one click: {unsubscribe_url}\n"
        f"Privacy Policy (PIPA): https://eztofind.ca/privacy\n"
    )


async def send_email(
    db,
    *,
    to: str,
    subject: str,
    html: str,
    text: str,
    kind: str,                       # "transactional" | "commercial"
    related_id: Optional[str] = None,  # e.g. saved_search.id
    unsubscribe_url: Optional[str] = None,
) -> dict:
    """Send an email. Behaviour depends on env:
    - RESEND_API_KEY set: post to Resend, log outcome to email_outbox.
    - Otherwise: log to email_outbox with status='pending' (queued for later).

    ALL commercial messages MUST include a CASL footer with sender ID +
    unsubscribe link. Callers should build `html` and `text` bodies
    that include their own copy PLUS the footer output from
    casl_footer_html / casl_footer_text.
    """
    outbox_doc = {
        "to": to,
        "subject": subject,
        "html": html,
        "text": text,
        "kind": kind,
        "related_id": related_id,
        "unsubscribe_url": unsubscribe_url,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "status": "pending",
        "provider": "resend" if RESEND_API_KEY else "outbox",
        "attempts": 0,
    }

    if not RESEND_API_KEY:
        outbox_doc["reason"] = "RESEND_API_KEY not configured — message queued"
        r = await db.email_outbox.insert_one(outbox_doc)
        logger.info(f"[email queued] to={to} subject={subject[:60]} kind={kind}")
        return {"queued": True, "id": str(r.inserted_id), "provider": "outbox"}

    # Send via Resend
    payload = {
        "from": RESEND_FROM,
        "to": [to],
        "subject": subject,
        "html": html,
        "text": text,
    }
    if unsubscribe_url:
        payload["headers"] = {
            # RFC 8058 one-click list-unsubscribe (Gmail + Outlook honour this)
            "List-Unsubscribe": f"<{unsubscribe_url}>",
            "List-Unsubscribe-Post": "List-Unsubscribe=One-Click",
        }
    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            r = await client.post(RESEND_URL, json=payload, headers={
                "Authorization": f"Bearer {RESEND_API_KEY}",
                "Content-Type": "application/json",
            })
        outbox_doc["attempts"] = 1
        outbox_doc["provider_response_status"] = r.status_code
        if r.status_code < 300:
            body = r.json()
            outbox_doc["status"] = "sent"
            outbox_doc["provider_message_id"] = body.get("id")
            outbox_doc["sent_at"] = datetime.now(timezone.utc).isoformat()
            await db.email_outbox.insert_one(outbox_doc)
            logger.info(f"[email sent] to={to} subject={subject[:60]} id={body.get('id')}")
            return {"queued": False, "provider": "resend", "provider_message_id": body.get("id")}
        else:
            outbox_doc["status"] = "error"
            outbox_doc["provider_error"] = r.text[:600]
            await db.email_outbox.insert_one(outbox_doc)
            logger.warning(f"[email error] Resend {r.status_code}: {r.text[:200]}")
            return {"queued": False, "provider": "resend", "error": r.text[:200], "status_code": r.status_code}
    except Exception as e:
        outbox_doc["status"] = "error"
        outbox_doc["provider_error"] = str(e)
        outbox_doc["attempts"] = 1
        await db.email_outbox.insert_one(outbox_doc)
        logger.exception(f"[email exception] {e}")
        return {"queued": False, "provider": "resend", "error": str(e)}
