// FamilyViewingParty — /family-viewing-party
//
// GOAL: convert families who want to review a home together (grown-up
// kids, in-laws, remote spouses) into leads by showcasing the TV Pairing
// flow — the true-cast big-screen viewer at /tv that nobody else in BC
// real estate has.
//
// COMPLIANCE (1000% mandatory)
//   • BCFSA licensee + Disclosure of Representation link
//   • CREA reciprocity: MLS®/REALTOR® trademarks + DDF® attribution
//   • GVR: Doug's listing brokerage + address + phone on every render
//   • PIPA: privacy notice on the lead form + link to /privacy
//   • CASL: express-consent checkbox (opt-in, unchecked by default)
//   • Not-advice bumper (no property-specific advice from Doogie)
//
// AEO / AEG / LLM / SEO / CITATION
//   • JSON-LD: WebPage + HowTo + VideoObject + FAQPage + BreadcrumbList
//   • Cite-friendly step numbering + FAQ Q&A blocks
//   • Semantic <h1>/<h2>/<ol> hierarchy
//   • Open Graph + Twitter Card meta so shares render a big preview
//   • Canonical URL locked to https://eztofind.ca/family-viewing-party

import React, { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import { Helmet } from "react-helmet-async";
import { TurnstileWidget, getTurnstileToken } from "../App";

const API = process.env.REACT_APP_BACKEND_URL;
const CANONICAL = "https://eztofind.ca/family-viewing-party";

const C = {
  navy: "#0F2A5B", gold: "#F5A623", cream: "#F5F0E1",
  ink: "#1F2937", muted: "#6B7280", paper: "#FAFAF7",
  blue: "#1E4FCF", green: "#059669",
};

// ── Content ────────────────────────────────────────────────────────
const STEPS = [
  {
    n: 1, title: "Open any listing on your phone",
    body: "Browse the 40,000+ live MLS® listings on eztofind.ca. When you find one worth showing the family, tap the gold Cast button on the listing page.",
    icon: "📱",
  },
  {
    n: 2, title: "Get a 6-digit TV code",
    body: "Tap \"Get a TV pairing code\". Your phone will show a big 6-digit number and a QR that opens eztofind.ca/tv straight to the code screen.",
    icon: "🔢",
  },
  {
    n: 3, title: "On your TV, open eztofind.ca/tv",
    body: "Any TV browser works — Samsung Tizen, LG WebOS, or a laptop plugged into HDMI. Enter the code. The listing plays full-screen on the big TV — no mirroring, no lag, no black bars.",
    icon: "📺",
  },
  {
    n: 4, title: "Swipe through together",
    body: "Your phone becomes the remote. Swipe the photo carousel and everyone on the couch sees the next room. Tap \"Play Doogie narration\" and the AI walks the family through the listing on the TV speakers.",
    icon: "🎬",
  },
];

const WHY = [
  { icon: "🍿", title: "One TV, one room, one decision",
    body: "Skip the tiny-phone-passing routine. Everyone sees the same photo at the same time — better questions, faster consensus." },
  { icon: "🎧", title: "Doogie narrates on the TV, not your phone",
    body: "Our AI concierge reads a vision-grounded walk-through through the TV speakers so you can lean back and just listen." },
  { icon: "🌎", title: "Great for remote family",
    body: "Sharing with parents in another city? Send them the same 6-digit code and they can pop it into their own TV — you both view in sync." },
  { icon: "🔒", title: "No app, no login, no data harvesting",
    body: "The TV code is a temporary handshake (20 min TTL). Nothing about the session is retained past that — full PIPA compliance." },
];

const FAQ = [
  { q: "What TVs work with Family Viewing Party?",
    a: "Any TV that has a web browser or is connected to one. That includes every 2018+ Samsung (Tizen), LG (WebOS), and Google TV; a laptop HDMI'd to a TV; a Chromebook; or an iPad with a Lightning/USB-C HDMI adapter. Apple TV and older stock Chromecasts don't ship with a browser — for those, we still offer AirPlay Screen Mirroring as a fallback." },
  { q: "Is this different from just casting my phone?",
    a: "Yes. Screen-mirroring sends whatever is on your phone to the TV, which drains your battery and shows every notification. Family Viewing Party pairs a fresh browser session on the TV that plays the listing full-screen at native resolution. Your phone is just the remote — turn the screen off and the show keeps playing." },
  { q: "Does the TV need to be signed in to anything?",
    a: "No. Open a web browser on the TV, go to eztofind.ca/tv, enter the 6-digit code your phone shows, done. No email, no password, no CASL trigger." },
  { q: "How long does a pairing session last?",
    a: "20 minutes from the last activity. If the family wants to review a second listing after that, the phone generates a new code with one tap." },
  { q: "Can Doogie really narrate on the TV?",
    a: "Yes. When you tap \"Play Doogie narration\" on the phone remote, the TV browser fetches a vision-grounded walk-through script for the listing (generated by our Claude Sonnet 4.6 photo-grounded AI, cached server-side) and plays it back through the TV speakers using OpenAI's Onyx voice. Doogie's narration is general information only — not property-specific advice." },
  { q: "Is this compliant with GVR, CREA, and BCFSA?",
    a: "Yes. Every listing rendered on the TV carries the CREA MLS®/REALTOR® trademarks, the listing brokerage attribution (GVR §3.14), and Doug's own BCFSA licensee credit. Personal information collected on the phone is handled under BC's Personal Information Protection Act (PIPA); marketing emails require separate CASL express consent." },
  { q: "What does it cost?",
    a: "$0. The feature is included with every buyer who uses eztofind.ca. Doug is compensated by the seller's brokerage on any resulting purchase under BC's Multiple Listing Service® rules — never by you." },
];

// ── Animated illustration: phone → TV handshake ─────────────────────
// Pure CSS + inline SVG so it works everywhere, including preview
// crawlers.  Ships as the hero visual until we record a real 15 s demo
// clip.  Placed inside a Helmet-friendly <div> so screen readers skip
// via aria-hidden.
const HeroIllustration = () => (
  <div aria-hidden="true" style={{
    position: "relative", width: "100%", maxWidth: 720, aspectRatio: "16 / 9",
    margin: "0 auto", background: "linear-gradient(135deg, #0F2A5B 0%, #1E4FCF 60%, #143a86 100%)",
    borderRadius: 24, overflow: "hidden", boxShadow: "0 40px 80px rgba(15,42,91,0.35)",
  }}>
    <style>{`
      @keyframes fvp-phone-glow { 0%,100% { box-shadow: 0 0 0 rgba(245,166,35,0); } 50% { box-shadow: 0 0 48px rgba(245,166,35,0.55); } }
      @keyframes fvp-signal-pulse { 0% { transform: scale(0.5); opacity:1; } 100% { transform: scale(2.4); opacity:0; } }
      @keyframes fvp-tv-frame-in { 0%,25% { opacity:0; transform: translateY(20px) scale(0.94);} 45%,100% { opacity:1; transform: translateY(0) scale(1);} }
      @keyframes fvp-photo-swap { 0%,20% { background-position: 0% 50%; } 40%,60% { background-position: 50% 50%; } 80%,100% { background-position: 100% 50%; } }
    `}</style>

    {/* Phone */}
    <div style={{
      position: "absolute", left: "5%", top: "50%", transform: "translateY(-50%)",
      width: "18%", aspectRatio: "9 / 19", background: "#0b1f45",
      border: "3px solid #F5A623", borderRadius: 18,
      display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
      animation: "fvp-phone-glow 2.6s ease-in-out infinite",
      padding: "8px 4px",
    }}>
      <div style={{ color: "#F5A623", fontSize: "0.55rem", letterSpacing: "0.14em", textTransform: "uppercase", fontWeight: 800, marginBottom: 6 }}>
        Code
      </div>
      <div style={{
        color: "#fff", fontFamily: "Sora,monospace", fontWeight: 800,
        letterSpacing: "0.15em", fontSize: "clamp(0.75rem, 2.2vw, 1.1rem)",
      }}>730363</div>
      <div style={{ marginTop: 8, height: 3, width: "60%", background: "#F5A623", borderRadius: 3 }}/>
      <div style={{ marginTop: 4, height: 2, width: "45%", background: "rgba(255,255,255,0.35)", borderRadius: 2 }}/>
      <div style={{ marginTop: 2, height: 2, width: "40%", background: "rgba(255,255,255,0.35)", borderRadius: 2 }}/>
    </div>

    {/* Signal rings */}
    <div style={{
      position: "absolute", left: "24%", top: "50%", transform: "translate(-50%,-50%)",
      width: 100, height: 100, borderRadius: "50%",
      border: "2px solid #F5A623", animation: "fvp-signal-pulse 2.4s ease-out infinite",
    }}/>
    <div style={{
      position: "absolute", left: "24%", top: "50%", transform: "translate(-50%,-50%)",
      width: 100, height: 100, borderRadius: "50%",
      border: "2px solid #F5A623", animation: "fvp-signal-pulse 2.4s ease-out 0.8s infinite",
    }}/>
    <div style={{
      position: "absolute", left: "24%", top: "50%", transform: "translate(-50%,-50%)",
      width: 100, height: 100, borderRadius: "50%",
      border: "2px solid #F5A623", animation: "fvp-signal-pulse 2.4s ease-out 1.6s infinite",
    }}/>

    {/* TV */}
    <div style={{
      position: "absolute", right: "5%", top: "50%", transform: "translateY(-50%)",
      width: "55%", aspectRatio: "16 / 10", background: "#000",
      border: "6px solid #1a1a1a", borderRadius: 12,
      display: "flex", overflow: "hidden",
      animation: "fvp-tv-frame-in 3.2s ease-out infinite",
      boxShadow: "0 24px 40px rgba(0,0,0,0.5)",
    }}>
      {/* photo pane */}
      <div style={{
        flex: 1, backgroundImage: "linear-gradient(90deg, #6d8fbf 0%, #a8c4e6 25%, #f1c27d 50%, #8cbf95 75%, #6d8fbf 100%)",
        backgroundSize: "400% 100%", animation: "fvp-photo-swap 6s ease-in-out infinite",
        display: "flex", alignItems: "flex-end", padding: "10px 12px",
      }}>
        <div style={{ background: "rgba(0,0,0,0.55)", color: "#fff", padding: "3px 8px", borderRadius: 999, fontSize: "0.6rem", fontFamily: "Sora,sans-serif", fontWeight: 700 }}>3 / 5</div>
      </div>
      {/* sidecar */}
      <div style={{
        width: "38%", background: "linear-gradient(180deg,#0F2A5B 0%,#08183a 100%)",
        borderLeft: "3px solid #F5A623", padding: "10px 12px",
        display: "flex", flexDirection: "column", justifyContent: "center", color: "#fff",
      }}>
        <div style={{ fontSize: "0.55rem", opacity: 0.7, letterSpacing: "0.12em", textTransform: "uppercase", fontWeight: 700 }}>
          Big screen
        </div>
        <div style={{ color: "#F5A623", fontFamily: "Sora,sans-serif", fontWeight: 800, fontSize: "clamp(0.85rem, 2vw, 1.2rem)", marginTop: 2 }}>
          $1.20M
        </div>
        <div style={{ fontFamily: "Sora,sans-serif", fontWeight: 700, fontSize: "0.68rem", marginTop: 2 }}>
          410 Government St
        </div>
        <div style={{ opacity: 0.75, fontSize: "0.6rem", marginTop: 2 }}>
          Victoria, BC · 3 bed · 4 bath
        </div>
      </div>
    </div>
  </div>
);

// ── Small primitives ──────────────────────────────────────────────
const H2 = ({ children, id }) => (
  <h2 id={id} style={{
    fontFamily: "Sora,sans-serif", fontSize: "clamp(1.6rem, 3.5vw, 2.4rem)",
    fontWeight: 800, color: C.navy, margin: "0 0 1rem", letterSpacing: "-0.01em",
  }}>{children}</h2>
);

const Card = ({ children, style, ...rest }) => (
  <div style={{
    background: "#fff", border: `1px solid rgba(15,42,91,0.1)`, borderRadius: 16,
    padding: "1.5rem", boxShadow: "0 6px 20px rgba(15,42,91,0.06)",
    ...(style || {}),
  }} {...rest}>{children}</div>
);

// ── Lead form ─────────────────────────────────────────────────────
function LeadForm() {
  const [f, setF] = useState({
    name: "", email: "", phone: "",
    intent: "Buying in BC",
    property_type: "",
    areas: "",
    notes: "",
    consent_pipa: false,
    consent_casl: false,
  });
  const [state, setState] = useState("idle"); // idle | submitting | done | error
  const [err, setErr] = useState("");

  const submit = async (e) => {
    e.preventDefault();
    setErr("");
    if (!f.consent_pipa) { setErr("Please tick the PIPA acknowledgement to submit."); return; }
    setState("submitting");
    try {
      await axios.post(`${API}/api/leads/buyer`, {
        full_name: f.name, email: f.email, phone: f.phone,
        property_type: f.property_type || "Any",
        areas: f.areas ? f.areas.split(",").map(x => x.trim()).filter(Boolean) : ["Any"],
        budget_range: "Not specified",
        timeline: "Family Viewing Party — flexible",
        financing_status: "Not specified",
        first_time_buyer: false,
        working_with_realtor: false,
        preferred_contact: "email",
        notes: `[Family Viewing Party lead — intent: ${f.intent}] ${f.notes || ""}`.trim(),
        casl_consent: f.consent_casl,
        pipa_ack: f.consent_pipa,
        source: "family-viewing-party",
        form_lang: "en",
        turnstile_token: getTurnstileToken(),
      });
      setState("done");
    } catch (x) {
      setState("error");
      setErr("We couldn't submit that just now. Please text Doug at (604) 787-0851 and we'll get you set up manually.");
    }
  };

  if (state === "done") {
    return (
      <Card style={{ background: C.cream, borderColor: "rgba(245,166,35,0.35)" }} data-testid="fvp-lead-success">
        <div style={{ fontSize: "3rem", textAlign: "center", marginBottom: "0.5rem" }}>🎉</div>
        <h3 style={{ fontFamily: "Sora,sans-serif", color: C.navy, margin: "0 0 0.5rem", textAlign: "center" }}>
          You're on the list — Doug will send you 3 hand-picked listings within 24 hours.
        </h3>
        <p style={{ margin: 0, color: C.muted, textAlign: "center", fontSize: "0.9rem" }}>
          Each one is Family-Viewing-Party ready. Cast on your phone → enter the code → pop popcorn.
        </p>
      </Card>
    );
  }

  return (
    <Card data-testid="fvp-lead-form">
      <h3 style={{ fontFamily: "Sora,sans-serif", color: C.navy, margin: "0 0 0.35rem", fontSize: "1.35rem" }}>
        Ready to host your first Family Viewing Party?
      </h3>
      <p style={{ margin: "0 0 1rem", color: C.muted, fontSize: "0.9rem" }}>
        Give Doug your must-haves — he'll pick 3 live MLS® listings that look great on the big screen and send them within 24 hours.
      </p>
      <form onSubmit={submit} style={{ display: "grid", gap: "0.75rem" }}>
        <input required placeholder="Your name" value={f.name}
               onChange={(e) => setF({ ...f, name: e.target.value })}
               data-testid="fvp-name" style={inputStyle} autoComplete="name"/>
        <input required type="email" placeholder="Email" value={f.email}
               onChange={(e) => setF({ ...f, email: e.target.value })}
               data-testid="fvp-email" style={inputStyle} autoComplete="email"/>
        <input placeholder="Phone (optional)" value={f.phone}
               onChange={(e) => setF({ ...f, phone: e.target.value })}
               data-testid="fvp-phone" style={inputStyle} autoComplete="tel"/>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.5rem" }}>
          <select value={f.intent} onChange={(e) => setF({ ...f, intent: e.target.value })}
                  data-testid="fvp-intent" style={inputStyle}>
            <option>Buying in BC</option>
            <option>Selling in BC</option>
            <option>Just browsing / research</option>
            <option>Relocating to BC</option>
          </select>
          <input placeholder="Property type (e.g. Detached, Condo)" value={f.property_type}
                 onChange={(e) => setF({ ...f, property_type: e.target.value })}
                 data-testid="fvp-property-type" style={inputStyle}/>
        </div>
        <input placeholder="Preferred areas (comma-separated: Maple Ridge, Langley)"
               value={f.areas}
               onChange={(e) => setF({ ...f, areas: e.target.value })}
               data-testid="fvp-areas" style={inputStyle}/>
        <textarea placeholder="Anything Doug should know (budget range, timeline, must-haves)…"
                  value={f.notes} rows={3}
                  onChange={(e) => setF({ ...f, notes: e.target.value })}
                  data-testid="fvp-notes"
                  style={{ ...inputStyle, resize: "vertical", minHeight: 72 }}/>

        {/* PIPA */}
        <label style={consentStyle} data-testid="fvp-consent-pipa-label">
          <input type="checkbox" checked={f.consent_pipa}
                 onChange={(e) => setF({ ...f, consent_pipa: e.target.checked })}
                 data-testid="fvp-consent-pipa"
                 style={{ marginTop: 3 }}/>
          <span>
            <strong>Required:</strong> I acknowledge that this information will be collected and used by Doug LeMaire, REALTOR® and Fraser Property Management Realty Services Ltd. to provide real-estate services under the BC Personal Information Protection Act (PIPA). See the <Link to="/privacy" style={{ color: C.blue, textDecoration: "underline" }}>Privacy Policy</Link>.
          </span>
        </label>

        {/* CASL — express, opt-in, unchecked by default */}
        <label style={consentStyle} data-testid="fvp-consent-casl-label">
          <input type="checkbox" checked={f.consent_casl}
                 onChange={(e) => setF({ ...f, consent_casl: e.target.checked })}
                 data-testid="fvp-consent-casl"
                 style={{ marginTop: 3 }}/>
          <span>
            <strong>Optional:</strong> Yes, please email me new listings that match my criteria, the Doug LeMaire weekly BC market note, and occasional Family-Viewing-Party features. I understand I can unsubscribe with one click under Canada's Anti-Spam Legislation (CASL).
          </span>
        </label>

        <TurnstileWidget/>

        {err && <div data-testid="fvp-error" style={{ color: "#B91C1C", fontSize: "0.85rem" }}>⚠️ {err}</div>}

        <button type="submit" disabled={state === "submitting"}
                data-testid="fvp-submit"
                style={{
                  background: state === "submitting" ? "#9CA3AF" : C.gold,
                  color: C.navy, border: "none", borderRadius: 999,
                  padding: "0.9rem 1.2rem", fontFamily: "Sora,sans-serif", fontWeight: 800,
                  fontSize: "1rem", cursor: state === "submitting" ? "progress" : "pointer",
                  boxShadow: "0 6px 16px rgba(245,166,35,0.35)",
                }}>
          {state === "submitting" ? "Sending…" : "🍿 Send me 3 party-ready listings"}
        </button>
        <div style={{ fontSize: "0.75rem", color: C.muted, textAlign: "center" }}>
          $0 obligation. Doug is compensated by the seller's brokerage on any completed BC purchase under MLS® rules.
        </div>
      </form>
    </Card>
  );
}

const inputStyle = {
  padding: "0.7rem 0.85rem", border: `1px solid rgba(15,42,91,0.2)`, borderRadius: 10,
  fontSize: "0.95rem", fontFamily: "Inter,sans-serif", background: "#fff",
  outline: "none", color: C.ink,
};
const consentStyle = {
  display: "grid", gridTemplateColumns: "18px 1fr", gap: "0.55rem",
  fontSize: "0.82rem", color: C.ink, lineHeight: 1.5, cursor: "pointer",
  background: C.paper, padding: "0.65rem 0.85rem", borderRadius: 10,
  border: "1px solid rgba(15,42,91,0.1)",
};

// ── Page ───────────────────────────────────────────────────────────
export default function FamilyViewingParty() {
  const jsonLd = useMemo(() => ({
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": `${CANONICAL}#webpage`,
        url: CANONICAL,
        name: "Family Viewing Party — Watch BC MLS® Listings on the Big Screen",
        description: "Cast any MLS® listing from your phone to your TV with a 6-digit code — no app, no mirroring. Turn family Sunday into a home-tour night.",
        inLanguage: "en-CA",
        isPartOf: { "@type": "WebSite", "@id": "https://eztofind.ca#site", name: "EZtoFind.ca", url: "https://eztofind.ca" },
        breadcrumb: {
          "@type": "BreadcrumbList",
          itemListElement: [
            { "@type": "ListItem", position: 1, name: "Home", item: "https://eztofind.ca" },
            { "@type": "ListItem", position: 2, name: "Family Viewing Party", item: CANONICAL },
          ],
        },
      },
      {
        "@type": "HowTo",
        name: "How to cast a BC MLS® listing from your phone to your TV",
        description: "Turn any MLS® listing on eztofind.ca into a big-screen family viewing without mirroring your phone.",
        totalTime: "PT2M",
        estimatedCost: { "@type": "MonetaryAmount", currency: "CAD", value: "0" },
        supply: [
          { "@type": "HowToSupply", name: "Any phone with a web browser" },
          { "@type": "HowToSupply", name: "A TV with a browser (Samsung Tizen, LG WebOS, Chromebook + HDMI, or laptop + HDMI)" },
        ],
        step: STEPS.map(s => ({
          "@type": "HowToStep",
          position: s.n,
          name: s.title,
          text: s.body,
        })),
      },
      {
        "@type": "VideoObject",
        name: "Family Viewing Party — 15-second demo",
        description: "A quick look at how phone → TV pairing works on eztofind.ca. No mirroring, no app, no login.",
        thumbnailUrl: "https://eztofind.ca/og/family-viewing-party.jpg",
        uploadDate: "2026-02-13",
        contentUrl: `${CANONICAL}#demo`,
        embedUrl: `${CANONICAL}#demo`,
        publisher: { "@type": "Organization", name: "EZtoFind.ca", url: "https://eztofind.ca" },
      },
      {
        "@type": "FAQPage",
        mainEntity: FAQ.map(({ q, a }) => ({
          "@type": "Question",
          name: q,
          acceptedAnswer: { "@type": "Answer", text: a },
        })),
      },
      {
        "@type": "RealEstateAgent",
        "@id": "https://eztofind.ca#agent",
        name: "Doug LeMaire",
        jobTitle: "REALTOR®",
        image: "https://eztofind.ca/doug.jpg",
        telephone: "+1-604-787-0851",
        email: "doug@eztofind.ca",
        url: "https://eztofind.ca",
        worksFor: {
          "@type": "RealEstateAgent",
          name: "Fraser Property Management Realty Services Ltd.",
          telephone: "+1-604-466-7021",
          address: {
            "@type": "PostalAddress",
            streetAddress: "1 – 22374 Lougheed Hwy",
            addressLocality: "Maple Ridge",
            addressRegion: "BC",
            postalCode: "V2X 2T5",
            addressCountry: "CA",
          },
        },
        areaServed: ["Greater Vancouver", "Fraser Valley", "Sea-to-Sky"],
      },
    ],
  }), []);

  return (
    <div style={{ background: C.paper, color: C.ink, fontFamily: "Inter,sans-serif" }}>
      <Helmet>
        <title>Family Viewing Party — Watch BC MLS® Listings on the Big Screen | EZtoFind.ca</title>
        <meta name="description" content="Cast any BC MLS® listing from your phone to your TV in 3 taps — no app, no mirroring, no login. Turn family Sunday into a home-tour night with Doug LeMaire's Family Viewing Party." />
        <meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large" />
        <link rel="canonical" href={CANONICAL} />
        {/* Open Graph */}
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="EZtoFind.ca" />
        <meta property="og:title" content="Family Viewing Party — Watch BC MLS® Listings on the Big Screen" />
        <meta property="og:description" content="Cast any MLS® listing from your phone to your TV in 3 taps. No app, no mirroring. Turn family Sunday into a home-tour night." />
        <meta property="og:url" content={CANONICAL} />
        <meta property="og:image" content="https://eztofind.ca/og/family-viewing-party.jpg" />
        {/* Twitter */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Family Viewing Party — BC MLS® Listings on the Big Screen" />
        <meta name="twitter:description" content="Phone → TV in 3 taps. No app, no mirroring, no login. eztofind.ca" />
        <meta name="twitter:image" content="https://eztofind.ca/og/family-viewing-party.jpg" />
        <script type="application/ld+json">{JSON.stringify(jsonLd)}</script>
      </Helmet>

      {/* Not-advice bumper */}
      <div style={{ background: C.navy, color: "#fff", fontSize: "0.78rem", padding: "0.45rem 1rem", textAlign: "center" }}>
        EZtoFind.ca provides <strong>general educational information</strong> about BC real estate — not legal, tax, financial, or property-specific advice.
      </div>

      {/* ── HERO ────────────────────────────────────────────────── */}
      <section style={{
        background: `linear-gradient(135deg, ${C.navy} 0%, #143a86 60%, ${C.blue} 100%)`,
        color: "#fff", padding: "3rem 1.25rem 2.5rem",
      }} aria-labelledby="fvp-hero-h1">
        <div style={{ maxWidth: 1180, margin: "0 auto" }}>
          <nav aria-label="Breadcrumb" style={{ fontSize: "0.78rem", opacity: 0.75, marginBottom: "0.75rem" }}>
            <Link to="/" style={{ color: "#fff", opacity: 0.8, textDecoration: "none" }}>Home</Link>
            <span style={{ margin: "0 0.4rem" }}>›</span>
            <span>Family Viewing Party</span>
          </nav>
          <div style={{
            display: "inline-block", background: C.gold, color: C.navy,
            padding: "3px 10px", borderRadius: 4, fontSize: "0.72rem",
            fontWeight: 800, letterSpacing: "0.14em", textTransform: "uppercase",
            marginBottom: "0.75rem",
          }}>New · BC-first feature</div>
          <h1 id="fvp-hero-h1" style={{
            fontFamily: "Sora,sans-serif", fontSize: "clamp(2rem, 5vw, 3.4rem)",
            fontWeight: 800, margin: "0 0 0.75rem", letterSpacing: "-0.01em",
            lineHeight: 1.1, maxWidth: 900,
          }}>
            🍿 Family Viewing Party — watch any BC MLS® listing on the big screen.
          </h1>
          <p style={{ margin: "0 0 1.5rem", opacity: 0.9, fontSize: "clamp(1rem, 2vw, 1.15rem)", maxWidth: 780 }}>
            No app. No screen-mirroring. No login. Cast any listing from your phone to your TV in 3 taps — the family sees the same photo, at native resolution, on the couch. Your phone becomes the remote.
          </p>
          <div style={{ marginBottom: "1.5rem" }}>
            <HeroIllustration/>
          </div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "0.75rem" }}>
            <Link to="/listings" data-testid="fvp-hero-cta-search"
                  style={{
                    background: C.gold, color: C.navy, padding: "0.85rem 1.5rem",
                    borderRadius: 999, textDecoration: "none",
                    fontFamily: "Sora,sans-serif", fontWeight: 800, fontSize: "1rem",
                    boxShadow: "0 6px 16px rgba(245,166,35,0.35)",
                  }}>
              🔍 Pick a listing to cast →
            </Link>
            <a href="#lead" data-testid="fvp-hero-cta-lead"
               style={{
                 background: "transparent", color: "#fff",
                 border: "1.5px solid rgba(255,255,255,0.5)",
                 padding: "0.85rem 1.5rem", borderRadius: 999, textDecoration: "none",
                 fontFamily: "Sora,sans-serif", fontWeight: 700, fontSize: "1rem",
               }}>
              📩 Send me 3 party-ready listings
            </a>
          </div>
          <div style={{ marginTop: "1rem", fontSize: "0.82rem", opacity: 0.85 }}>
            Works on Samsung Tizen · LG WebOS · Chromebook + HDMI · Laptop + HDMI · iPad + HDMI adapter · Apple TV / Chromecast via mirror fallback
          </div>
        </div>
      </section>

      {/* ── STEPS ─────────────────────────────────────────────── */}
      <section id="how-it-works" style={{ padding: "3rem 1.25rem", maxWidth: 1180, margin: "0 auto" }} aria-labelledby="fvp-steps-h2">
        <H2 id="fvp-steps-h2">How it works</H2>
        <p style={{ maxWidth: 720, color: C.muted, margin: "0 0 2rem", fontSize: "1rem" }}>
          Four steps, about two minutes. If you can order pizza on your phone, you can do this.
        </p>
        <ol style={{
          display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
          gap: "1rem", padding: 0, margin: 0, listStyle: "none",
        }}>
          {STEPS.map(s => (
            <li key={s.n}>
              <Card data-testid={`fvp-step-${s.n}`} style={{ height: "100%" }}>
                <div style={{ display: "flex", alignItems: "center", gap: "0.6rem", marginBottom: "0.5rem" }}>
                  <div style={{
                    width: 34, height: 34, borderRadius: "50%",
                    background: C.navy, color: "#fff",
                    display: "flex", alignItems: "center", justifyContent: "center",
                    fontFamily: "Sora,sans-serif", fontWeight: 800, fontSize: "1rem",
                  }}>{s.n}</div>
                  <div style={{ fontSize: "1.6rem" }} aria-hidden>{s.icon}</div>
                </div>
                <h3 style={{ fontFamily: "Sora,sans-serif", fontSize: "1.1rem", color: C.navy, margin: "0 0 0.4rem" }}>
                  {s.title}
                </h3>
                <p style={{ margin: 0, color: C.ink, fontSize: "0.9rem", lineHeight: 1.55 }}>{s.body}</p>
              </Card>
            </li>
          ))}
        </ol>
      </section>

      {/* ── WHY ───────────────────────────────────────────────── */}
      <section style={{ background: C.cream, padding: "3rem 1.25rem" }} aria-labelledby="fvp-why-h2">
        <div style={{ maxWidth: 1180, margin: "0 auto" }}>
          <H2 id="fvp-why-h2">Why families love it</H2>
          <div style={{
            display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
            gap: "1rem", marginTop: "1rem",
          }}>
            {WHY.map((w, i) => (
              <Card key={i} data-testid={`fvp-why-${i}`}>
                <div style={{ fontSize: "1.8rem", marginBottom: "0.5rem" }} aria-hidden>{w.icon}</div>
                <h3 style={{ fontFamily: "Sora,sans-serif", fontSize: "1.05rem", color: C.navy, margin: "0 0 0.4rem" }}>{w.title}</h3>
                <p style={{ margin: 0, fontSize: "0.9rem", color: C.ink, lineHeight: 1.55 }}>{w.body}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* ── LEAD FORM ─────────────────────────────────────────── */}
      <section id="lead" style={{ padding: "3rem 1.25rem" }} aria-labelledby="fvp-lead-h2">
        <div style={{ maxWidth: 720, margin: "0 auto" }}>
          <H2 id="fvp-lead-h2">Get 3 hand-picked, party-ready listings</H2>
          <p style={{ color: C.muted, margin: "0 0 1.5rem", fontSize: "1rem" }}>
            Tell Doug what you're looking for. Within 24 hours he'll send 3 live MLS® listings that look great on the big screen — plus the 6-digit codes so you can cast them straight to your TV tonight.
          </p>
          <LeadForm/>
        </div>
      </section>

      {/* ── FAQ ───────────────────────────────────────────────── */}
      <section id="faq" style={{ background: "#fff", padding: "3rem 1.25rem" }} aria-labelledby="fvp-faq-h2">
        <div style={{ maxWidth: 900, margin: "0 auto" }}>
          <H2 id="fvp-faq-h2">Questions families ask</H2>
          <div style={{ display: "grid", gap: "0.75rem" }}>
            {FAQ.map((f, i) => (
              <details key={i} data-testid={`fvp-faq-${i}`}
                       style={{ background: C.paper, borderRadius: 12, border: `1px solid rgba(15,42,91,0.1)`, padding: "0.85rem 1.1rem" }}>
                <summary style={{ cursor: "pointer", fontFamily: "Sora,sans-serif", fontWeight: 700, color: C.navy, fontSize: "1rem" }}>
                  {f.q}
                </summary>
                <p style={{ margin: "0.65rem 0 0", color: C.ink, fontSize: "0.92rem", lineHeight: 1.6 }}>{f.a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* ── COMPLIANCE FOOTER ─────────────────────────────────── */}
      <footer style={{ background: C.navy, color: "#fff", padding: "2.5rem 1.25rem", fontSize: "0.85rem" }}>
        <div style={{ maxWidth: 1180, margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", marginBottom: "0.75rem" }}>
            <div style={{ fontSize: "0.72rem", background: C.gold, color: C.navy, padding: "3px 8px", borderRadius: 4, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase" }}>Regulatory</div>
            <div style={{ fontSize: "0.95rem", fontWeight: 700, fontFamily: "Sora,sans-serif" }}>
              Doug LeMaire, REALTOR® · Fraser Property Management Realty Services Ltd. · BCFSA-licensed
            </div>
          </div>
          <p style={{ margin: "0 0 0.5rem" }}>
            <strong>Brokerage:</strong> Fraser Property Management Realty Services Ltd., 1 – 22374 Lougheed Hwy, Maple Ridge, BC V2X 2T5. Brokerage: <a href="tel:604-466-7021" style={{ color: C.gold }}>(604) 466-7021</a> · Doug direct: <a href="tel:604-787-0851" style={{ color: C.gold }}>(604) 787-0851</a>.
          </p>
          <p style={{ margin: "0 0 0.5rem", opacity: 0.88 }}>
            MLS®, Multiple Listing Service®, REALTOR®, REALTORS®, and the REALTOR® logo are certification marks owned by The Canadian Real Estate Association (CREA) and identify real-estate professionals who are members of CREA. Property data © CREA Data Distribution Facility (DDF®), sourced live from Greater Vancouver REALTORS® (GVR), Fraser Valley Real Estate Board, and 10+ participating BC boards. Refreshed every 4 hours.
          </p>
          <p style={{ margin: "0 0 0.5rem", opacity: 0.88 }}>
            General information only — <strong>not legal, tax, financial, or property-specific advice</strong>. For your own situation, always speak with a BC lawyer or notary, an accountant, a licensed mortgage broker, and a REALTOR®. Doug is not the listing agent for any property shown on this site unless explicitly stated; always verify all information directly with the listing brokerage before making an offer.
          </p>
          <p style={{ margin: 0, opacity: 0.88 }}>
            Personal information collected on this site is handled under the BC Personal Information Protection Act (PIPA) — see the <Link to="/privacy" style={{ color: C.gold }}>Privacy Policy</Link>. Marketing email consent is recorded under Canada's Anti-Spam Legislation (CASL) — <Link to="/email-preferences" style={{ color: C.gold }}>unsubscribe any time</Link>. Read Doug's <Link to="/terms" style={{ color: C.gold }}>Terms of Service</Link> and full <Link to="/disclosure" style={{ color: C.gold }}>Disclosure of Representation</Link>.
          </p>
        </div>
      </footer>
    </div>
  );
}
